apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-myschool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: spring-boot-container
          image: khawlacherni/myschool:latest   # Replace with your actual image name and version
          ports:
            - containerPort: 8080   # Expose the port your Spring Boot app is running on
          env:
            - name: DB_HOST
              value: mysql-service   # Replace with the name of your MySQL Service
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: myschool        # Replace with your actual database name
            - name: DB_USERNAME
              value: root            # Replace with your actual database username
            - name: DB_PASSWORD
              value: ""              # Replace with your actual database password


---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot
  ports:
    - protocol: TCP
      port: 80   # Port on which the service will listen
      targetPort: 8080   # Port on which the Spring Boot app is running

