apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-myschool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: spring-boot-container
          image: khawlacherni/myschoolpfe:latest   # Replace with your actual image name and version
          ports:
            - containerPort: 8080   # Expose the port your Spring Boot app is running on
          env:
            - name: JAVA_OPTS
              value: "-Xmx150m" # Replace with your actual database password
            - name: DB_URL
              value: "jdbc:mysql://192.168.1.46:30473/jpetstore?allowPublicKeyRetrieval=true&useSSL=false
"

          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot
  ports:
    - protocol: TCP
      port: 8081   # Port on which the service will listen
      targetPort: 8080   # Port on which the Spring Boot app is running
  type: NodePort